name: main_2
on:
  workflow_dispatch:
    inputs:
      aaa:
        description: 'input AAA'
        required: true
        default: 1
        
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
          first_naem: ${{ github.event.inputs.aaa }}
    
      
